
spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    
  messages:
    basename: "i18n/messages"
    cache-duration: -1
    encoding: UTF-8

# env setting
  data:    mongodb:      # SPRING: SPRING_DATA_MONGODB_HOST
      host: 192.168.99.102
      # SPRING: SPRING_DATA_MONGODB_PORT
      port: 32775
      # SPRING: SPRING_DATA_MONGODB_USERNAME
      # DOCKER: MONGODB_USERNAME
      username: springboot
      # SPRING: SPRING_DATA_MONGODB_PASSWORD
      # DOCKER: MONGODB_PASSWORD
      password: springboot
      # SPRING: SPRING_DATA_MONGODB_DATABASE
      # DOCKER: MONGODB_DATABASE
      database: springboot

logging:  level:
    root: OFF    com.example: DEBUG
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG